### ISSUE TITLE
Add home-assistant machine specifications to README

### ISSUE THREAD

**Issue by hpdubs** [geekofweek/homeassistant#13]
I'm more curious about what you use to run your setup and could be helpful for others.

**Comment by geekofweek** [comment]
Not sure I fully follow what the issue / request is here.  From a hardware perspective I list out all components used for integrations in [README.md](https://github.com/geekofweek/homeassistant/blob/master/README.md).  The server that runs Home Assistant is listed out as part of the [Other Hardware](https://github.com/geekofweek/homeassistant/blob/master/README.md#other) section, which is an Intel NUC running Ubuntu and Docker. 

Is there something in particular that is missing?

**Comment by hpdubs** [comment]
Doh - sorry - I see it now.
