### ISSUE TITLE
Question about configs

### ISSUE THREAD

**Issue by shauntarves** [geekofweek/homeassistant#21]
Heyo,

First off, I love this repo. I've learned so much about HA by perusing your automations. I've recently run into a few issues of my own and am struggling to understand _why_ you've chosen some of the approaches you did.

Specifically, why didn't you leverage scenes to simplify some of the automations you have? It seems there are quite a few "conditions" that get duplicated in the automations, which screams "scene" to me. I'm curious if you encountered problems with scenes. I feel conflicted whenever I go to add new automated functionality in my own HA instance. Like, is "turning off the climate control system" best defined by a "scene" or by an automation that affects multiple entities?

Anyway, would love to hear your thoughts on this!

**Comment by shauntarves** [comment]
Thanks for the response. It appears there has been a definite melding of functionality over time - especially with scripts + automations.

If I were approaching this with a fresh eye, I might say that automations should trigger scripts that control scenes. So many ways to skin the cat!

**Comment by geekofweek** [comment]
Lots of my stuff just came out of what was capable at the time, I try to keep up with updating as things change but I don’t always get around to it.
