### ISSUE TITLE
Light Group

### ISSUE THREAD

**Issue by greigallen** [geekofweek/homeassistant#22]
I noticed that your light_group.yaml file is missing from your repo but it is still linked in your README.md file, was it deleted in error?

I would be interested to see how you have your light groups set up 🙂

**Comment by geekofweek** [comment]
I should have deleted that reference.  I did use light_group.yaml for a long time but switched it over to groups created via the helpers UI.  Same groups just done via the UI instead of yaml

**Comment by geekofweek** [comment]
[light_group.txt](https://github.com/geekofweek/homeassistant/files/10363380/light_group.txt)

I dug up an old version from before migrating it, that should be about what it was
