### ISSUE TITLE
Binary Sensors

### ISSUE THREAD

**Issue by thabet-h** [geekofweek/homeassistant#5]
Awesome setup, geekofweek

Could you possibly share your binary_sensors.yaml? Would help to understand how you designed your occupancy sensors.

Thanks!

**Comment by geekofweek** [comment]
I don't actually have a binary_sensors.yaml, it's all handled by the Ecobee room sensors so it's part of that component.

**Comment by thabet-h** [comment]
Thanks for the reply.

Are you using the Ecobee sensors for presence detection / occupancy somehow?

**Comment by geekofweek** [comment]
Correct.  When you add the Ecobee component it adds two devices per remote sensor.  A sensor for temperature and a binary_sensor for occupancy
